### ISSUE TITLE
Neither contact.html nor about.html have been built out.

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#1]
Hi, @rafed 
Again, it's me... I'm trying your [exampleSite](https://github.com/rafed/BlogRa/tree/main/exampleSite) directly. 

I just grabbed your [exampleSite](https://github.com/rafed/BlogRa/tree/main/exampleSite) FIRST, and then, put **theme/BlogRa** under this [exampleSite](https://github.com/rafed/BlogRa/tree/main/exampleSite). Afterwards, I tried to build by `hugo`, but **contact** and **about** are **NOT** built out. I mean, under folder **public**, **Neither contact.html nor about.html** have been built out.

Any suggestions please???

**Comment by rafed** [comment]
I tested it out and everything seems to work correctly. 

Make sure that:
1. Contents of exampleSite (i.e about, admin, contact ...) are in your content folder
2. config.toml of exampleSite is placed in the root of the project

If it still does not work, upload your project and let me have a look. :)

**Comment by jiapei100** [comment]
Yeah... this time, it seems working.... Thank you very much...

And, some of the files are named as **_index.md**, with a underscore in front. For instance, there is one with contents:

```
---
title: "DevRa"
subtitle: "The Practical Software Engineering Blog"
date: 2020-03-25T04:52:30+06:00
draft: false
---
```

It looks it has nothing to do with the entire website?

**Comment by rafed** [comment]
It has something to do with the website. _index.md pages mark its parent directory as a section. Try changing the values and you'll see it has effects.
