### ISSUE TITLE
Looking forward to a footer or at least customized social media?

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#13]
Please take a look at here: [https://www.longervision.ca/about/](https://www.longervision.ca/about/) .

I would like to add some additional social media (or business ads) beyound your current ones, say:

**yelp**, and **yellowpage** ...

Any suggestions?

Thank you

**Comment by rafed** [comment]
You can edit this file: https://github.com/rafed/BlogRa/blob/main/layouts/partials/social-media-presence.html  to include additional icons (if they are available on font-awesome).

Also, do consider sending in PRs to this repo.

**Comment by jiapei100** [comment]
Thanks for your reply... ^_^
I found **yelp** in font-awesome, but **NOT yellow-page**.
Anyway, thank you very much...
