### ISSUE TITLE
Keep seeing error when using image on my posts

### ISSUE THREAD

**Issue by basvandewiel** [rafed/BlogRa#14]
My apologies if this is a 100% newbie mistake, but I keep receiving this error:

`Error: error building site: render: failed to render pages: render of "page" failed: "/home/bvdwiel/Projects/area536/themes/BlogRa/layouts/_default/baseof.html:5:8": execute of template failed: template: _default/single.html:5:8: executing "_default/single.html" at <partial "head-metadata.html" .>: error calling partial: "/home/bvdwiel/Projects/area536/themes/BlogRa/layouts/partials/head-metadata.html:13:3": execute of template failed: template: partials/head-metadata.html:13:3: executing "partials/head-metadata.html" at <partial "seo.html" .>: error calling partial: "/home/bvdwiel/Projects/area536/themes/BlogRa/layouts/partials/seo.html:59:30": execute of template failed: template: partials/seo.html:59:30: executing "partials/seo.html" at <$image.Permalink>: nil pointer evaluating resource.Resource.Permali`

I copied the config.toml example from your docs verbatim as well as the front matter example but I still get this error, no matter where I place the image. Looking at the partial I tried using a remote image, which does gets me though the process without errors but I end up with an empty homepage.

Any pointers for fixing this would be highly appreciated.

**Comment by rafed** [comment]
Can you link me to your source code, please?

**Comment by basvandewiel** [comment]
I restarted from scratch and uploaded a bare-bones minimal site where the exact issue occurs:

https://github.com/basvandewiel/area536

This is a completely clean-slate restart of my project so I may well be missing stuff now.

**Comment by rafed** [comment]
Hmm this is weird...

<img width="1227" alt="image" src="https://github.com/rafed/BlogRa/assets/10649912/c11f7e32-019b-4cd3-ada3-ff86a8c999aa">

I cloned and served your repo, it seems to compile for me. I'm using hugo version v0.112.7+extended though...

**Comment by basvandewiel** [comment]
Arch offers a later Hugo version 0.115-DEV as part of the AUR collection. I cloned my own repo, did a git submodule --init and then tried hugo. It gives the same error message:

sh-5.1$ hugo
Start building sites … 
hugo v0.115.0-DEV-941818295d10a00ef557bce30ee9df86affc9f0f+extended linux/amd64 BuildDate=2023-06-20T12:25:37Z

Total in 418 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/home/bvdwiel/Projects/area536/themes/BlogRa/layouts/_default/baseof.html:5:8": execute of template failed: template: _default/single.html:5:8: executing "_default/single.html" at <partial "head-metadata.html" .>: error calling partial: "/home/bvdwiel/Projects/area536/themes/BlogRa/layouts/partials/head-metadata.html:13:3": execute of template failed: template: partials/head-metadata.html:13:3: executing "partials/head-metadata.html" at <partial "seo.html" .>: error calling partial: "/home/bvdwiel/Projects/area536/themes/BlogRa/layouts/partials/seo.html:59:30": execute of template failed: template: partials/seo.html:59:30: executing "partials/seo.html" at <$image.Permalink>: nil pointer evaluating resource.Resource.Permalink

**Comment by rafed** [comment]
The version you are using now is a dev version. Could you please try using a stable version and let me know whether that works or not?
