### ISSUE TITLE
FIRST page opened up with weird signs/characters ?

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#16]
Whenever I **FIRST-time** open up my webiste [https://longervision.ca/](https://longervision.ca/), I can see some empty squres (weird characters or signs?) Please refer to:
![1285966778](https://github.com/rafed/BlogRa/assets/154013/08403e3c-9516-4c50-890c-3775131beb76)

And, after I click the top-left corner icon, I got
![2089329322](https://github.com/rafed/BlogRa/assets/154013/ccd64aa4-2d51-421b-b38c-be8e6a573da6)

Afterwards, I click **Home**, I can get the correct display as:
![1427524253](https://github.com/rafed/BlogRa/assets/154013/65fb3b78-5216-4ad6-9f93-478d6c9450e0)

Any suggestions? And why is it so?

**Comment by rafed** [comment]
The server you are using is slow in sending out the images, so the browser meanwhile shows boxes instead of the real images. I suggest you choose a faster server. (e.g maybe opt for github pages)
