### ISSUE TITLE
How to order those blogs NOT by published date BUT by given indexes?

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#17]
How to order those blogs NOT by published date BUT by given indexes?

Please refer to my page at: [https://www.longervision.ca/highschool/](https://www.longervision.ca/highschool/) ... It looks messy. I would like them to be grouped up in a particular sequence. But how?

**Comment by out-of-order** [comment]
This is not an issue.

**Comment by out-of-order** [comment]
hugo 113 throws a warning. Is there any reason to be concerned of that for the future?

`The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/home/micro/hugo/klima/content/posts/rich content/index.md:22:1"`
