### ISSUE TITLE
Warning on twitter shortcode

### ISSUE THREAD

**Issue by out-of-order** [rafed/BlogRa#19]
hugo 113 throws a warning:

`The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/home/user/hugo/klima/content/posts/rich content/index.md:22:1"`

I personally don't use the twitter shortcode. So it is just enough for me to do:
```
[privacy.twitter]
    disable = true
```

Though this can be set manually maybe an updated release would fix that so there would be no warnings on a fresh install.

**Comment by rafed** [comment]
Thanks. Will be addressed in latest release.
