### ISSUE TITLE
Can I remove fontawesome-free-5.15.1-web and bootstrap-5.0.0 in assets?

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#2]
It looks the packages of fontawesome-free-5.15.1-web and bootstrap-5.0.0 are out-of-date, there are **newer** versions, and what if I `npm install` both packages globally? Will that influence those `*.scss` files under **assets** ?

**Comment by rafed** [comment]
Unless you have intentions of modifying the ui I see no reason why bootstrap should be updated. 

Global bootstrap installation will not affect the hugo theme.
