### ISSUE TITLE
How to categorize posts in different pages ?

### ISSUE THREAD

**Issue by jiapei100** [rafed/BlogRa#7]
Hi, can you please take a look at [https://longervision.ca/curricula/](https://longervision.ca/curricula/) . I've got multiple pages now, due to more and more posts. How can I specify, say:
- page 1: Robotics (may not be over 1 page, say: 9 items)
- page 2: coding (may not be over 1 page, say: 9 items)
- ???
Thank you

**Comment by rafed** [comment]
If I understand your question correctly, you can categorize posts using "sections". Take a look here: https://github.com/rafed/BlogRa/tree/main/exampleSite/content to check how posts can be grouped. They will also appear under home and posts if kept here.
