### ISSUE TITLE
Image Links instead  of files

### ISSUE THREAD

**Issue by grybro** [rafed/BlogRa#8]
Hi, is it possible to modify the theme to allow image links instead of files in posts.  I've used this in other themes and was hoping it was possible in yours.
I'm talking about the "image:" variable.
Thanks!

**Comment by rafed** [comment]
Hi gybro, thanks for using BlogRa.

Hmm, that's interesting. It's definitely possible. I don't think I have the time to do this at the moment. Do you think you can make a PR?

**Comment by grybro** [comment]
No worries. I didn't expect you to be able to do it so soon.
But are you asking me to make Pull Request?  Don't wouldn't I have to make the changes first to do that?  Not sure I'm skilled enough in hugo themes yet, but working on it.

BTW - Very happy with the Theme and work you did.  Appreciate you allowing it to be available for use. Really nice job.

**Comment by rafed** [comment]
You can try to make a PR, I'll help if needed. Otherwise, you might need to give me some more time so that I can start on it.

**Comment by rafed** [comment]
@grybro The feature has been added. You can now try it out.
