### ISSUE TITLE
favicon not displaying

### ISSUE THREAD

**Issue by grybro** [rafed/BlogRa#9]
Hi,
Is this a bug?
`<link rel="icon" type="image/png" href="{{ .Site.BaseURL }}image/favicon.ico">`
in the file head-metadata.html

or should it be "images/favicon.ico"?

thanks.

**Comment by rafed** [comment]
Provided that the favicon.ico is inside the static folder, this should be ok.

Are you having trouble displaying the favicon?

**Comment by grybro** [comment]
That's correct.  It doesn't work for me.  I even tried to copy over your examplesite, but that didn't work either.
When I change "image" to "images" and put the file in static/images that worked for me.
